/* aero_core C ABI — generated by cbindgen. Do not edit by hand. */

#ifndef AERO_CORE_H
#define AERO_CORE_H

#pragma once

/* Warning: this file is auto-generated. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Arbitrum One, the chain a deposit or withdrawal touches.
 */
#define AeroARBITRUM_CHAIN_ID 42161

/**
 * Deposits below this are ignored by the bridge and are hard to recover.
 */
#define AeroMIN_DEPOSIT_USDC 5.0

/**
 * Flat fee the exchange charges to withdraw to Arbitrum.
 */
#define AeroWITHDRAW_FEE_USDC 1.0

/**
 * USB data-transfer packet size for all Trezor models (Section "USB packet size").
 */
#define AeroUSB_PACKET_SIZE 64

/**
 * Broadcast channel used for channel allocation requests/responses.
 */
#define AeroCID_BROADCAST 65535

#define AeroCHANNEL_ALLOCATION_REQUEST 64

#define AeroCHANNEL_ALLOCATION_RESPONSE 65

#define AeroTRANSPORT_ERROR 66

#define AeroPING 67

#define AeroPONG 68

#define AeroCONTINUATION 128

#define AeroHANDSHAKE_INIT_REQUEST 0

#define AeroHANDSHAKE_INIT_RESPONSE 1

#define AeroHANDSHAKE_COMPLETION_REQUEST 2

#define AeroHANDSHAKE_COMPLETION_RESPONSE 3

#define AeroENCRYPTED_TRANSPORT 4

#define AeroACK 32

#define AeroACK_BIT 8

#define AeroSEQ_BIT 16

#define AeroSYNC_MASK (AeroACK_BIT | AeroSEQ_BIT)

#define AeroFAILURE 3

#define AeroSUCCESS 2

#define AeroBUTTON_REQUEST 26

#define AeroBUTTON_ACK 27

#define AeroTHP_CREATE_NEW_SESSION 1000

#define AeroTHP_PAIRING_REQUEST 1008

#define AeroTHP_PAIRING_REQUEST_APPROVED 1009

#define AeroTHP_SELECT_METHOD 1010

#define AeroTHP_PAIRING_PREPARATIONS_FINISHED 1011

#define AeroTHP_CREDENTIAL_REQUEST 1016

#define AeroTHP_CREDENTIAL_RESPONSE 1017

#define AeroTHP_END_REQUEST 1018

#define AeroTHP_END_RESPONSE 1019

#define AeroTHP_CODE_ENTRY_COMMITMENT 1024

#define AeroTHP_CODE_ENTRY_CHALLENGE 1025

#define AeroTHP_CODE_ENTRY_CPACE_TREZOR 1026

#define AeroTHP_CODE_ENTRY_CPACE_HOST_TAG 1027

#define AeroTHP_CODE_ENTRY_SECRET 1028

#define AeroETHEREUM_GET_ADDRESS 56

#define AeroETHEREUM_SIGN_TX 58

#define AeroETHEREUM_ADDRESS 57

#define AeroETHEREUM_SIGN_TX_EIP1559 452

#define AeroETHEREUM_TX_REQUEST 59

#define AeroETHEREUM_TX_ACK 60

#define AeroSKIP_PAIRING 1

#define AeroCODE_ENTRY 2

#define AeroQR_CODE 3

#define AeroNFC 4

/**
 * Product id of the known THP-capable/WebUSB models. Others are reported, not rejected.
 */
#define AeroPID_WEBUSB 21441

#define AeroUNPAIRED 0

#define AeroPAIRED 1

#define AeroPAIRED_AUTOCONNECT 2

/**
 * Piconero per XMR.
 */
#define AeroATOMIC_PER_XMR 1000000000000

typedef struct AeroWallet AeroWallet;

/**
 * Asks the user for the 6-digit code the Trezor is displaying during pairing.
 *
 * Unlike every other call here, this one runs the other way round: the core invokes it partway
 * through a blocking operation, on whichever worker thread is driving the device. An
 * implementation that touches the UI must therefore marshal to the UI thread itself.
 *
 * Write the code as NUL-terminated ASCII into `out` (at most `out_len` bytes including the
 * terminator) and return 0. Return non-zero if the user cancelled.
 */
typedef int (*AeroPairingCodeFn)(void *ctx,
                                 char *out,
                                 int out_len);

/**
 * The Aero release signing key, as raw Ed25519 public key bytes.
 *
 * Pinned, not looked up. There is no keyring, no key server and no way for a downloaded file to
 * nominate the key that verifies it - the only key that can ever authorise an update to this build
 * is the one compiled into it. Replacing the key therefore requires replacing Aero, which is the
 * property we want: an attacker who can serve you a manifest still cannot serve you a key.
 *
 * Primary key of:
 *     pub   ed25519 2026-09-05 [SC] [expires: 2029-09-05]
 *           FD06 516B 6C76 2BB8 B016  16DE 80D5 05C2 5B02 54B3
 *     uid   Aero
 */
#define AeroRELEASE_KEY { 131, 50, 212, 130, 6, 138, 62, 65, 33, 242, 37, 122, 23, 94, 252, 158, 89, 80, 21, 9, 251, 232, 214, 70, 99, 213, 0, 133, 41, 68, 72, 177, }

/**
 * V4 fingerprint of [`RELEASE_KEY`]: SHA-1 over the public-key packet body, per RFC 4880 section 12.2.
 * Shown to the user so the key in the app can be compared against the one published elsewhere.
 */
#define AeroRELEASE_FINGERPRINT { 253, 6, 81, 107, 108, 118, 43, 184, 176, 22, 22, 222, 128, 213, 5, 194, 91, 2, 84, 179, }

/**
 * USB vendor ids Trezor ships under: 0x1209 (pid.codes, Model T and later) and 0x534C (the
 * original SatoshiLabs id used by the Model One).
 */
#define AeroTREZOR_VIDS { 4617, 21324, }

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the last error message for the current thread, or NULL if none.
 * Caller must free with [`aero_string_free`].
 */
char *aero_last_error(void);

/**
 * Semantic version of the core library.
 */
char *aero_version(void);

/**
 * Configure Trezor-Host Protocol support: where to keep the pairing credential, and how to ask
 * the user for the pairing code.
 *
 * `credential_path` should be an app-level location so a device is paired once for all wallets.
 * Passing a NULL callback disables pairing: already-paired devices keep working, but a device
 * that needs pairing reports an error rather than hanging.
 *
 * # Safety
 * `credential_path` must be a valid NUL-terminated string. `ctx` must remain valid for as long as
 * the callback is registered.
 */
void aero_thp_configure(const char *credential_path,
                        AeroPairingCodeFn callback,
                        void *ctx);

/**
 * Whether a Trezor has already been paired, i.e. whether connecting will be silent. 1 = yes.
 */
int aero_thp_is_paired(void);

/**
 * Forget the stored pairing, so the next connection pairs afresh. Returns 0 on success.
 */
int aero_thp_forget_pairing(void);

/**
 * Drop any cached device connection. Call when a wallet is closed so the device is released.
 */
void aero_thp_disconnect(void);

/**
 * Free a string returned by this library.
 */
void aero_string_free(char *s);

/**
 * Free a string that carried SECRET material (mnemonic / exported private key), zeroizing the
 * bytes first so the plaintext doesn't linger in freed heap. Callers use this instead of
 * `aero_string_free` for `aero_wallet_mnemonic` / `aero_wallet_export_private_key`.
 */
void aero_secret_string_free(char *s);

/**
 * Create a new wallet with a fresh random mnemonic (`word_count` = 12 or 24).
 */
AeroWallet *aero_wallet_create_new(uint32_t word_count);

/**
 * Create a new wallet with a fresh mnemonic and an optional BIP39 passphrase (empty/NULL = none).
 */
AeroWallet *aero_wallet_create_new_with_passphrase(uint32_t word_count,
                                                   const char *passphrase);

/**
 * Restore a wallet from a BIP39 mnemonic.
 */
AeroWallet *aero_wallet_restore(const char *mnemonic);

/**
 * Restore a wallet from a BIP39 mnemonic with an optional passphrase (empty/NULL = none). A
 * different passphrase derives a completely different set of addresses.
 */
AeroWallet *aero_wallet_restore_with_passphrase(const char *mnemonic,
                                                const char *passphrase);

/**
 * Whether the wallet's HD tree is protected by a BIP39 passphrase (1 = yes, 0 = no).
 */
int aero_wallet_has_passphrase(AeroWallet *w);

/**
 * List connected devices of `kind` ("ledger"/"trezor") as a JSON array of names. Caller frees.
 */
char *aero_wallet_hw_list_devices(const char *kind);

/**
 * Create a watch-only hardware wallet by deriving `num_accounts` addresses from the connected
 * device. `passphrase` is the host-entered BIP39 passphrase (Trezor); NULL/"" = none.
 */
AeroWallet *aero_wallet_create_hardware(const char *kind,
                                        const char *passphrase,
                                        uint32_t num_accounts);

/**
 * Open a hardware wallet file. Requires the device (and its passphrase, if any); fails if the
 * device is absent or derives a different first address.
 */
AeroWallet *aero_wallet_open_hardware(const char *path,
                                      const char *password,
                                      const char *passphrase);

/**
 * Inspect a wallet file without a device: 1 = hardware wallet, 0 = software wallet, -1 = can't
 * decrypt (wrong password / unreadable). Lets the open flow decide whether to prompt for a device.
 */
int aero_wallet_file_is_hardware(const char *path,
                                 const char *password);

/**
 * Whether the wallet's keys live on a hardware device (1 = yes, 0 = no).
 */
int aero_wallet_is_hardware(AeroWallet *w);

/**
 * The 0-based imported-key ordinal for the account at `index`, or -1 when it is seed-derived (or the
 * index is out of range). Lets the UI label imported accounts distinctly from HD accounts.
 */
int aero_wallet_account_imported_ordinal(AeroWallet *w, uint32_t index);

/**
 * Create an address-only watch wallet from a JSON array of 0x addresses (e.g. `["0x..","0x.."]`).
 * No keys are stored; balances/history work but signing/sending is refused.
 */
AeroWallet *aero_wallet_watch_only(const char *addresses_json);

/**
 * Whether the wallet is an address-only watch wallet (1 = yes, 0 = no).
 */
int aero_wallet_is_watch_only(AeroWallet *w);

/**
 * Hardware device kind ("ledger"/"trezor"), or "" for software wallets. Caller frees.
 */
char *aero_wallet_hw_kind(AeroWallet *w);

/**
 * Derive and append one more hardware account from the device; returns its index (u32::MAX on error).
 */
uint32_t aero_wallet_hw_add_account(AeroWallet *w);

/**
 * Open an encrypted wallet file with a password.
 */
AeroWallet *aero_wallet_open(const char *path,
                             const char *password);

/**
 * Encrypt and save the wallet to `path`. Returns 0 on success, -1 on failure.
 */
int aero_wallet_save(AeroWallet *w,
                     const char *path,
                     const char *password);

/**
 * Release a wallet handle.
 */
void aero_wallet_free(AeroWallet *w);

/**
 * Return the wallet mnemonic (handle with care in the UI). Caller frees the string.
 */
char *aero_wallet_mnemonic(AeroWallet *w);

uint32_t aero_wallet_account_count(AeroWallet *w);

/**
 * Derive/track a new account; returns its index (or u32::MAX on error).
 */
uint32_t aero_wallet_add_account(AeroWallet *w);

/**
 * Import a raw hex private key as a new account; returns its index (or u32::MAX on error).
 */
uint32_t aero_wallet_import_private_key(AeroWallet *w,
                                        const char *hex_key);

/**
 * Return the checksummed 0x address for `index`. Caller frees the string.
 */
char *aero_wallet_address(AeroWallet *w,
                          uint32_t index);

/**
 * Export the raw 0x-prefixed private key hex for `index`. Caller frees the string. Sensitive.
 */
char *aero_wallet_export_private_key(AeroWallet *w,
                                     uint32_t index);

/**
 * EIP-191 personal_sign of `message` (UTF-8) with account `index`. Returns 0x-prefixed 65-byte
 * signature hex; null on error. Caller frees the string.
 */
char *aero_wallet_sign_message(AeroWallet *w,
                               uint32_t index,
                               const char *message);

/**
 * Recover the signer address of an EIP-191 personal_sign `signature` over `message`. Returns the
 * checksummed address hex; null on error (bad signature). Caller frees the string.
 */
char *aero_wallet_verify_message(const char *message,
                                 const char *signature);

/**
 * Track an ERC20 token in the wallet's Tokens/Assets panel.
 */
int aero_wallet_add_token(AeroWallet *w,
                          const char *address,
                          const char *symbol,
                          uint8_t decimals);

int aero_wallet_remove_token(AeroWallet *w,
                             const char *address);

/**
 * JSON array of tracked tokens. Caller frees the string.
 */
char *aero_wallet_tokens(AeroWallet *w);

/**
 * Per-wallet metadata JSON blob (labels/contacts/notes/funded). "" if none. Caller frees. This is
 * stored encrypted inside the wallet file, not in plaintext settings.
 */
char *aero_wallet_metadata(AeroWallet *w);

/**
 * Replace the per-wallet metadata JSON blob. Persisted (encrypted) on the next `aero_wallet_save`.
 * Returns 0 on success, -1 on error.
 */
int aero_wallet_set_metadata(AeroWallet *w,
                             const char *json);

/**
 * Configure the Tor-routed RPC provider.
 * `endpoints_json` is a JSON array of RPC URLs; `socks_proxy` may be NULL to disable Tor.
 * With no proxy, remote endpoints are refused unless `allow_clearnet` is true (a deliberate,
 * IP-exposing opt-out of Tor); localhost endpoints (your own node / Helios) are always allowed.
 */
int aero_wallet_set_provider(AeroWallet *w,
                             uint64_t chain_id,
                             const char *endpoints_json,
                             const char *socks_proxy,
                             bool allow_clearnet,
                             uint64_t timeout_secs);

/**
 * Point history for `chain_id` at explorer APIs of the caller's choosing, ahead of the built-in
 * ones. `csv` is a comma-separated list of bases; NULL or empty restores the built-ins.
 *
 * Each entry is either a host, to which `/api` is appended, or a URL that already carries a query
 * string, which is used as given - so `https://api.etherscan.io/v2/api?chainid=1&apikey=…` works,
 * as does a private Blockscout. This exists so that an explorer going away or tightening its limits
 * is a setting somebody changes rather than a release everybody has to install.
 */
void aero_set_history_apis(uint64_t chain_id,
                           const char *csv);

/**
 * ETH balance for `index` as JSON `BalanceInfo`. Caller frees the string.
 */
char *aero_wallet_eth_balance(AeroWallet *w,
                              uint32_t index);

/**
 * Native + tracked-token balances for accounts `0..num_accounts` in one batched request.
 * Returns JSON `{ native_symbol, accounts: [ { index, native_raw, native_formatted,
 * native_symbol, tokens: [ { address, symbol, decimals, raw, formatted } ] } ] }`.
 * Caller frees the string.
 */
char *aero_wallet_all_balances(AeroWallet *w,
                               uint32_t num_accounts,
                               const char *extra_tokens_json);

/**
 * ERC20 balance as JSON `BalanceInfo`. Caller frees the string.
 */
char *aero_wallet_erc20_balance(AeroWallet *w,
                                const char *token,
                                uint32_t index);

/**
 * Suggested EIP-1559 fees as JSON `FeeSuggestion`. Caller frees the string.
 */
char *aero_wallet_suggest_fees(AeroWallet *w);

/**
 * ETH/USD price (from the on-chain Chainlink feed, over Tor) as a decimal string. Caller frees.
 */
char *aero_wallet_eth_usd_price(AeroWallet *w);

/**
 * USD price of the connected chain's native coin (Chainlink on mainnet, CoinGecko elsewhere).
 * Decimal string; caller frees.
 */
char *aero_wallet_native_usd_price(AeroWallet *w);

/**
 * Deepest DEX pool USD liquidity for a token (via DexScreener over Tor), as a decimal string
 * ("0" on error / no pools). Caller frees the string.
 */
char *aero_wallet_token_liquidity_usd(AeroWallet *w,
                                      const char *token);

/**
 * Resolve an ERC-20's symbol + decimals (over Tor) as JSON `{"symbol","decimals"}`. Used by the
 * Send token picker when the user pastes an arbitrary contract address. Caller frees the string.
 */
char *aero_wallet_erc20_metadata(AeroWallet *w,
                                 const char *token);

/**
 * USD -> fiat conversion rate for `currency` (e.g. "eur"), via CoinGecko over Tor. 1.0 for "usd"
 * or on error. Used for the Settings fiat-currency display option. Caller frees the string.
 */
char *aero_wallet_fiat_per_usd(AeroWallet *w,
                               const char *currency);

/**
 * Current chain head block number (0 on error). Used for cheap new-block polling.
 */
uint64_t aero_wallet_block_number(AeroWallet *w);

/**
 * Market prices for the Home tickers as JSON `{"xmr_usd","xmr_chg","eth_usd","eth_chg"}` (fetched
 * over Tor). Caller frees the string.
 */
char *aero_wallet_market_prices(AeroWallet *w);

/**
 * Send ETH; returns JSON `SendResult` with the tx hash. `max_fee_wei`/`max_priority_wei` may be
 * NULL/"0" for an automatic fee. Caller frees the string.
 */
char *aero_wallet_send_eth(AeroWallet *w,
                           uint32_t from_index,
                           const char *to,
                           const char *amount_wei,
                           const char *max_fee_wei,
                           const char *max_priority_wei,
                           uint64_t nonce);

/**
 * Send an ERC20 token; returns JSON `SendResult`. Fee/nonce args as in `aero_wallet_send_eth`.
 */
char *aero_wallet_send_erc20(AeroWallet *w,
                             uint32_t from_index,
                             const char *token,
                             const char *to,
                             const char *amount_units,
                             const char *max_fee_wei,
                             const char *max_priority_wei,
                             uint64_t nonce);

/**
 * Historical USD spot price of `symbol` on `date` (YYYY-MM-DD) as a decimal string ("0" if
 * unavailable). Caller frees the string.
 */
char *aero_wallet_price_on_date(AeroWallet *w,
                                const char *symbol,
                                const char *date);

/**
 * "Pay to many": send to several recipients (one tx each, sequential nonces). `recipients_json` is
 * a JSON array of `["0xto","amountBaseUnits"]` pairs; `token` empty = native, else ERC-20 address.
 * Returns a JSON array of `{to, tx_hash}` / `{to, error}`. Caller frees the string.
 */
char *aero_wallet_send_many(AeroWallet *w,
                            uint32_t from_index,
                            const char *recipients_json,
                            const char *token,
                            const char *max_fee_wei,
                            const char *max_priority_wei);

/**
 * Atomic native multi-send via Multicall3 (one tx, all-or-nothing). `recipients_json` is a JSON
 * array of [address, decimal-wei]. Returns JSON `SendResult`. Caller frees the string.
 */
char *aero_wallet_send_many_native(AeroWallet *w,
                                   uint32_t from_index,
                                   const char *recipients_json,
                                   const char *max_fee_wei,
                                   const char *max_priority_wei);

/**
 * Replace-by-fee an arbitrary still-pending tx (found by hash) of `from_index`: `cancel`=true does
 * a 0-value self-send at its nonce; otherwise rebroadcasts the same tx at a higher fee (speed-up).
 * Returns JSON `SendResult`. Caller frees the string.
 */
char *aero_wallet_replace_tx(AeroWallet *w,
                             uint32_t from_index,
                             const char *tx_hash,
                             const char *max_fee_wei,
                             const char *max_priority_wei,
                             bool cancel);

/**
 * Broadcast an already-signed raw transaction (0x RLP hex) over the wallet's RPC/Tor. Returns JSON
 * `SendResult`. Works for watch-only wallets too (no keys needed). Caller frees the string.
 */
char *aero_wallet_broadcast_raw(AeroWallet *w,
                                const char *raw_hex);

/**
 * Build an UNSIGNED transaction (resolves nonce/gas/fees over the network) as JSON, for air-gapped
 * signing. `token` empty = native (uses `amount_wei`), else ERC-20 transfer (`amount_units`).
 * `nonce` = u64::MAX for automatic. Caller frees the string.
 */
char *aero_wallet_build_unsigned(AeroWallet *w,
                                 uint32_t from_index,
                                 const char *to,
                                 const char *amount_wei,
                                 const char *token,
                                 const char *amount_units,
                                 const char *max_fee_wei,
                                 const char *max_priority_wei,
                                 uint64_t nonce);

/**
 * Sign an unsigned-tx JSON (from `aero_wallet_build_unsigned`) with the local key; returns the 0x
 * raw RLP hex (no network needed - runs offline). Null on error. Caller frees the string.
 */
char *aero_wallet_sign_unsigned(AeroWallet *w,
                                const char *json);

/**
 * Cancel a pending tx by broadcasting a 0-value self-send at `nonce` with a (bumped) fee. Returns
 * JSON `SendResult`. Caller frees the string.
 */
char *aero_wallet_cancel_tx(AeroWallet *w,
                            uint32_t from_index,
                            uint64_t nonce,
                            const char *max_fee_wei,
                            const char *max_priority_wei);

/**
 * Fetch a CoW swap quote as JSON (the order fields live under `quote`). `sell_is_native` sells the
 * chain's wrapped-native token; pass the BUY_ETH sentinel as `buy_token` to receive native ETH.
 * Caller frees the string.
 */
char *aero_wallet_swap_quote(AeroWallet *w,
                             uint32_t from_index,
                             const char *sell_token,
                             const char *buy_token,
                             const char *sell_amount_wei,
                             bool sell_is_native);

/**
 * Current allowance of `token` (account `from_index`) to the CoW Vault Relayer, as a decimal-wei
 * string ("0" on error). Caller frees the string.
 */
char *aero_wallet_swap_allowance(AeroWallet *w,
                                 uint32_t from_index,
                                 const char *token);

/**
 * Approve the CoW Vault Relayer to spend `token`. `amount` is the decimal-wei cap; "max" (or empty)
 * approves an unlimited allowance. Returns JSON `SendResult`.
 */
char *aero_wallet_swap_approve(AeroWallet *w,
                               uint32_t from_index,
                               const char *token,
                               const char *amount);

/**
 * Sign (EIP-712) and submit the order from a CoW quote JSON. Returns the order UID string. Null on
 * error. Caller frees the string.
 */
char *aero_wallet_swap_submit(AeroWallet *w,
                              uint32_t from_index,
                              const char *quote_json,
                              uint32_t slippage_bps);

/**
 * Sell native ETH via CoW eth-flow (on-chain tx). `quote_json` from a quote taken with
 * `sell_is_native = true`; `buy_token` is the ERC-20 to receive. Returns JSON `SendResult`.
 */
char *aero_wallet_swap_eth_flow(AeroWallet *w,
                                uint32_t from_index,
                                const char *quote_json,
                                const char *buy_token,
                                uint32_t slippage_bps);

/**
 * Batched allowance scan. `tokens_json`/`spenders_json` are JSON arrays of addresses. Returns JSON
 * `{ "allowances": [ {token, spender, allowance}, … ] }` (non-zero only). Caller frees.
 */
char *aero_wallet_token_allowances(AeroWallet *w,
                                   uint32_t from_index,
                                   const char *tokens_json,
                                   const char *spenders_json);

/**
 * Revoke an ERC-20 approval (`approve(spender, 0)`). Returns JSON `SendResult`. Caller frees.
 */
char *aero_wallet_revoke_approval(AeroWallet *w,
                                  uint32_t from_index,
                                  const char *token,
                                  const char *spender);

/**
 * DefiLlama current prices for a comma-separated coin-key list. Returns the raw JSON. Caller frees.
 */
char *aero_wallet_defillama_prices(AeroWallet *w,
                                   const char *coins_csv);

/**
 * Fetch quotes from every keyless router supported on the current chain (parallel, over Tor).
 * `sell`/`buy` are token addresses; empty = native coin. Returns JSON `{ "quotes": [...] }`,
 * best-first. Caller frees the string.
 */
char *aero_wallet_swap_quotes(AeroWallet *w,
                              uint32_t from_index,
                              const char *sell,
                              const char *buy,
                              const char *sell_amount_wei,
                              bool sell_is_native,
                              uint8_t sell_decimals,
                              uint8_t buy_decimals,
                              uint32_t slippage_bps);

/**
 * Build the executable transaction for a chosen on-chain router (fresh calldata). Returns JSON
 * `{to, data, value, spender, buy_amount, min_buy_amount}`. Caller frees the string.
 */
char *aero_wallet_router_build(AeroWallet *w,
                               const char *router_id,
                               uint32_t from_index,
                               const char *sell,
                               const char *buy,
                               const char *sell_amount_wei,
                               bool sell_is_native,
                               uint8_t sell_decimals,
                               uint8_t buy_decimals,
                               uint32_t slippage_bps);

/**
 * Approve `spender` to spend `token`. `amount` is decimal-wei; "max"/empty = unlimited. Returns
 * JSON `SendResult`. Caller frees the string.
 */
char *aero_wallet_router_approve(AeroWallet *w,
                                 uint32_t from_index,
                                 const char *token,
                                 const char *spender,
                                 const char *amount);

/**
 * Current allowance of `token` (account `from_index`) to an arbitrary `spender`, as decimal-wei
 * ("0" on error). Caller frees the string.
 */
char *aero_wallet_router_allowance(AeroWallet *w,
                                   uint32_t from_index,
                                   const char *token,
                                   const char *spender);

/**
 * Send an arbitrary-calldata swap tx (`to`/`value`/`data` from `aero_wallet_router_build`). Returns
 * JSON `SendResult`. Caller frees the string.
 */
char *aero_wallet_router_swap(AeroWallet *w,
                              uint32_t from_index,
                              const char *to,
                              const char *value_wei,
                              const char *data_hex);

/**
 * What Across can bridge out of the connected chain right now, as JSON
 * `{origin_chain, assets:[{symbol, display, decimals, native, destinations:[chain_id]}]}`.
 * Fetched from Across itself, so retired assets stop being offered. Caller frees the string.
 */
char *aero_wallet_across_assets(AeroWallet *w);

/**
 * Everything the XMR1 trading screen shows, as JSON: the order book, the account's XMR1 and USDC
 * balances, its resting orders and its recent fills. Caller frees the string.
 */
char *aero_wallet_hl_overview(AeroWallet *w,
                              uint32_t index);

/**
 * Whether this account has already authorised Aero's trading key. Returns JSON `{"ready":bool}`.
 * Caller frees the string.
 */
char *aero_wallet_hl_agent_ready(AeroWallet *w,
                                 uint32_t index);

/**
 * Authorise Aero's trading key for this account - a one-time signature with the account key, after
 * which orders are signed by a key that cannot withdraw. Caller frees the string.
 */
char *aero_wallet_hl_approve_agent(AeroWallet *w,
                                   uint32_t index);

/**
 * Place an XMR1 order. `market_order` fills immediately at up to `price` and cancels any remainder;
 * otherwise the order rests at `price`. Returns JSON `{state, size, price, oid}` where `state` is
 * `filled`, `resting` or `none`. Caller frees the string.
 */
char *aero_wallet_hl_place_order(AeroWallet *w,
                                 uint32_t index,
                                 bool is_buy,
                                 double price,
                                 double size,
                                 bool market_order);

/**
 * Cancel a resting XMR1 order by its exchange order id. Caller frees the string.
 */
char *aero_wallet_hl_cancel_order(AeroWallet *w,
                                  uint32_t index,
                                  uint64_t oid);

/**
 * Move USDC from Arbitrum One onto the exchange by transferring it to Hyperliquid's bridge.
 * Requires the wallet to be connected to Arbitrum. Returns JSON `SendResult`. Caller frees.
 */
char *aero_wallet_hl_deposit(AeroWallet *w,
                             uint32_t index,
                             const char *amount_usdc);

/**
 * Withdraw USDC from the exchange back to this account's address on Arbitrum, minus the exchange's
 * flat fee. Signed by the account key, which an agent cannot do. Caller frees the string.
 */
char *aero_wallet_hl_withdraw(AeroWallet *w,
                              uint32_t index,
                              const char *amount_usdc);

/**
 * Move USDC between the perp (margin) and spot wallets on the exchange. `to_perp` true is spot to
 * perp; false is perp to spot, which makes a fresh bridge deposit spendable on the XMR1 book.
 * Signed by the account key. Caller frees the string.
 */
char *aero_wallet_hl_class_transfer(AeroWallet *w,
                                    uint32_t index,
                                    const char *amount_usdc,
                                    bool to_perp);

/**
 * What redeeming `amount_xmr1` of XMR1 for real Monero would cost: fee, minimum, and net payout.
 * Caller frees the string.
 */
char *aero_wallet_xmr_redeem_quote(AeroWallet *w,
                                   uint32_t index,
                                   const char *amount_xmr1);

/**
 * Redeem XMR1 for Monero paid to `monero_address`. Opens a Wagyu order and sends the XMR1 to the
 * address that order names. Returns the order id and session id needed to track it.
 * Caller frees the string.
 */
char *aero_wallet_xmr_redeem(AeroWallet *w,
                             uint32_t index,
                             const char *monero_address,
                             const char *amount_xmr1);

/**
 * Progress of a redemption. Caller frees the string.
 */
char *aero_wallet_xmr_redeem_status(AeroWallet *w,
                                    const char *order_id,
                                    const char *session_id);

/**
 * Across bridge fee quote for sending `amount_wei` of `symbol` from the connected chain to
 * `dest_chain_id`. Returns normalized JSON (output amount, fees, SpokePool, deposit params).
 * Caller frees the string.
 */
char *aero_wallet_across_quote(AeroWallet *w,
                               uint32_t from_index,
                               const char *symbol,
                               uint64_t dest_chain_id,
                               const char *amount_wei);

/**
 * Build the Across SpokePool `depositV3` transaction (fresh quote). Returns JSON
 * `{to, spender, data, value, native, output_amount, ...}`. Caller frees the string.
 */
char *aero_wallet_across_build(AeroWallet *w,
                               uint32_t from_index,
                               const char *symbol,
                               uint64_t dest_chain_id,
                               const char *amount_wei);

/**
 * ERC20 transfer history as a JSON array of `HistoryItem`. `from_block` is a hex block number
 * or "earliest"/"latest". Caller frees the string.
 */
char *aero_wallet_erc20_history(AeroWallet *w,
                                const char *token,
                                uint32_t index,
                                const char *from_block);

/**
 * Full account history (native ETH + all ERC20 transfers) for `index`, fetched from a block
 * explorer over Tor, as a JSON array of `HistoryItem`. Caller frees the string.
 */
char *aero_wallet_account_history(AeroWallet *w,
                                  uint32_t index);

/**
 * Transaction receipt JSON for `tx_hash` ("null" until mined; then an object with `status` +
 * `blockNumber`). Interactive priority (the UI polls this to confirm a send fast). Caller frees.
 */
char *aero_wallet_tx_receipt(AeroWallet *w,
                             const char *tx_hash);

/**
 * Resolve an ENS name (e.g. "alice.eth") to a checksummed 0x address (Ethereum mainnet only).
 * Returns the address string, or NULL on error (see aero_last_error). Caller frees.
 */
char *aero_wallet_resolve_ens(AeroWallet *w,
                              const char *name);

/**
 * CoW Protocol swap orders (pending + historical) for `index` from CoW's order-book API over Tor,
 * as a JSON array of swap `HistoryItem`s (with `status`). Caller frees the string.
 */
char *aero_wallet_cow_orders(AeroWallet *w,
                             uint32_t index);

/**
 * Request cooperative shutdown of all background network loops (funded scan, per-account history).
 * Called from the GUI's close handler so those loops stop and release the core lock promptly,
 * instead of the blocking close-time save waiting on an in-flight multi-minute scan/history.
 */
void aero_request_shutdown(void);

/**
 * Scan every common Ethereum derivation scheme for balances (Electrum-style multi-path recovery),
 * registering funded addresses as accounts and returning their unified indices as a JSON array.
 * Mutates the wallet, so it takes `&mut`. Caller frees the string.
 */
char *aero_wallet_scan_funded(AeroWallet *w,
                              uint32_t gap_limit);

/**
 * Scan for funded addresses across MULTIPLE chains. `configs_json` is a JSON array of
 * `{"chain_id":<u64>,"endpoints":["..."],"socks":"socks5h://..."}` (blank socks = direct).
 * Registers funded addresses as accounts and returns their unified indices as a JSON array.
 */
char *aero_wallet_scan_funded_multi(AeroWallet *w,
                                    const char *configs_json,
                                    uint32_t gap_limit);

/**
 * Read-only funded-address discovery for ONE chain. `config_json` is a single
 * `{"chain_id":<u64>,"endpoints":["..."],"socks":"..."}` object. Returns a JSON array of
 * `[scheme, index, path]` triples for aero_wallet_register_scanned to commit. Takes a shared borrow,
 * so the caller can hold a read lock and release it between chains (keeping add-account responsive).
 */
char *aero_wallet_scan_chain_paths(AeroWallet *w,
                                   const char *config_json,
                                   uint32_t gap_limit);

/**
 * Commit funded paths from aero_wallet_scan_chain_paths (JSON array of `[scheme, index, path]`).
 * Mutates the wallet but does no network I/O. Returns the registered unified indices as a JSON array.
 */
char *aero_wallet_register_scanned(AeroWallet *w,
                                   const char *found_json);

/**
 * Live progress of an in-flight funded scan: number of addresses checked so far. Lock-free; safe to
 * call from any thread while a scan runs on another. Reset to 0 when a scan starts.
 */
uint64_t aero_wallet_scan_progress(void);

/**
 * Live progress of an in-flight funded scan: number of funded addresses found so far. Lock-free.
 */
uint64_t aero_wallet_scan_found(void);

/**
 * Owned NFT collections (ERC-721 + ERC-1155) for an account as a JSON array. Caller frees.
 */
char *aero_wallet_account_nfts(AeroWallet *w,
                               uint32_t index);

/**
 * Fetch an image URL over Tor, hex-encoded ("" on error). Caller frees the string.
 */
char *aero_wallet_fetch_image(AeroWallet *w,
                              const char *url);

/**
 * The fingerprint of the key that must sign an update, for display. Caller frees.
 */
char *aero_update_key_fingerprint(void);

/**
 * Look for a newer signed release. `current` is this build's version, `socks` the Tor proxy (may be
 * NULL to go direct). Returns the update status as JSON, or NULL with [`aero_last_error`] set.
 *
 * An error here always means "could not establish that an update is genuine", never "no update".
 * A NULL return must not be shown to the user as "you are up to date".
 */
char *aero_update_check(const char *current,
                        const char *socks);

/**
 * Download the archive described by a status JSON from [`aero_update_check`] and check it against
 * the hash the signed manifest gave. Returns the archive path, or NULL on failure.
 *
 * The status must be the one this core produced; it is re-parsed rather than trusted as a handle,
 * and the download is rejected unless its length and hash match what it says.
 */
char *aero_update_download(const char *status_json,
                           const char *app_dir,
                           const char *socks);

/**
 * Bytes downloaded so far, and the total expected. Lock-free; poll from the UI thread.
 */
uint64_t aero_update_downloaded(void);

uint64_t aero_update_download_total(void);

/**
 * Abandon a download in flight. Safe to call at any time, from any thread.
 *
 * [`aero_update_download`] then fails with a message [`aero_update_was_cancelled`] recognises, so a
 * pressed Cancel button is not reported back to the user as a fault.
 */
void aero_update_cancel(void);

/**
 * Whether a message from [`aero_last_error`] describes a cancelled download rather than a failure.
 */
int aero_update_was_cancelled(const char *message);

/**
 * Unpack a downloaded archive into the staging folder. Returns 0 on success, -1 on failure.
 *
 * Nothing in the application folder is changed by this: staging exists so that a bad archive is
 * discovered while it is still off to one side.
 */
int aero_update_stage(const char *archive,
                      const char *app_dir);

/**
 * Install the staged update. Returns the number of files replaced, or -1 on failure.
 *
 * On failure nothing has changed: the install undoes itself rather than leaving a folder that is
 * half one version and half another.
 */
int aero_update_apply(const char *app_dir);

/**
 * Delete what the previous update displaced. Call once at startup; does nothing if there is none.
 */
void aero_update_sweep(const char *app_dir);

/**
 * Convert a human decimal string to base units (returns decimal string). Caller frees.
 */
char *aero_parse_units(const char *amount,
                       uint8_t decimals);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AERO_CORE_H */
