/* aero_core C ABI — generated by cbindgen. Do not edit by hand. */

#ifndef AERO_CORE_H
#define AERO_CORE_H

#pragma once

/* Warning: this file is auto-generated. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct AeroWallet AeroWallet;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the last error message for the current thread, or NULL if none.
 * Caller must free with [`aero_string_free`].
 */
char *aero_last_error(void);

/**
 * Semantic version of the core library.
 */
char *aero_version(void);

/**
 * Free a string returned by this library.
 */
void aero_string_free(char *s);

/**
 * Create a new wallet with a fresh random mnemonic (`word_count` = 12 or 24).
 */
AeroWallet *aero_wallet_create_new(uint32_t word_count);

/**
 * Create a new wallet with a fresh mnemonic and an optional BIP39 passphrase (empty/NULL = none).
 */
AeroWallet *aero_wallet_create_new_with_passphrase(uint32_t word_count,
                                                   const char *passphrase);

/**
 * Restore a wallet from a BIP39 mnemonic.
 */
AeroWallet *aero_wallet_restore(const char *mnemonic);

/**
 * Restore a wallet from a BIP39 mnemonic with an optional passphrase (empty/NULL = none). A
 * different passphrase derives a completely different set of addresses.
 */
AeroWallet *aero_wallet_restore_with_passphrase(const char *mnemonic,
                                                const char *passphrase);

/**
 * Whether the wallet's HD tree is protected by a BIP39 passphrase (1 = yes, 0 = no).
 */
int aero_wallet_has_passphrase(AeroWallet *w);

/**
 * List connected devices of `kind` ("ledger"/"trezor") as a JSON array of names. Caller frees.
 */
char *aero_wallet_hw_list_devices(const char *kind);

/**
 * Create a watch-only hardware wallet by deriving `num_accounts` addresses from the connected
 * device. `passphrase` is the host-entered BIP39 passphrase (Trezor); NULL/"" = none.
 */
AeroWallet *aero_wallet_create_hardware(const char *kind,
                                        const char *passphrase,
                                        uint32_t num_accounts);

/**
 * Open a hardware wallet file. Requires the device (and its passphrase, if any); fails if the
 * device is absent or derives a different first address.
 */
AeroWallet *aero_wallet_open_hardware(const char *path,
                                      const char *password,
                                      const char *passphrase);

/**
 * Inspect a wallet file without a device: 1 = hardware wallet, 0 = software wallet, -1 = can't
 * decrypt (wrong password / unreadable). Lets the open flow decide whether to prompt for a device.
 */
int aero_wallet_file_is_hardware(const char *path,
                                 const char *password);

/**
 * Whether the wallet's keys live on a hardware device (1 = yes, 0 = no).
 */
int aero_wallet_is_hardware(AeroWallet *w);

/**
 * Create an address-only watch wallet from a JSON array of 0x addresses (e.g. `["0x..","0x.."]`).
 * No keys are stored; balances/history work but signing/sending is refused.
 */
AeroWallet *aero_wallet_watch_only(const char *addresses_json);

/**
 * Whether the wallet is an address-only watch wallet (1 = yes, 0 = no).
 */
int aero_wallet_is_watch_only(AeroWallet *w);

/**
 * Hardware device kind ("ledger"/"trezor"), or "" for software wallets. Caller frees.
 */
char *aero_wallet_hw_kind(AeroWallet *w);

/**
 * Derive and append one more hardware account from the device; returns its index (u32::MAX on error).
 */
uint32_t aero_wallet_hw_add_account(AeroWallet *w);

/**
 * Open an encrypted wallet file with a password.
 */
AeroWallet *aero_wallet_open(const char *path,
                             const char *password);

/**
 * Encrypt and save the wallet to `path`. Returns 0 on success, -1 on failure.
 */
int aero_wallet_save(AeroWallet *w,
                     const char *path,
                     const char *password);

/**
 * Release a wallet handle.
 */
void aero_wallet_free(AeroWallet *w);

/**
 * Return the wallet mnemonic (handle with care in the UI). Caller frees the string.
 */
char *aero_wallet_mnemonic(AeroWallet *w);

uint32_t aero_wallet_account_count(AeroWallet *w);

/**
 * Derive/track a new account; returns its index (or u32::MAX on error).
 */
uint32_t aero_wallet_add_account(AeroWallet *w);

/**
 * Import a raw hex private key as a new account; returns its index (or u32::MAX on error).
 */
uint32_t aero_wallet_import_private_key(AeroWallet *w,
                                        const char *hex_key);

/**
 * Return the checksummed 0x address for `index`. Caller frees the string.
 */
char *aero_wallet_address(AeroWallet *w,
                          uint32_t index);

/**
 * Export the raw 0x-prefixed private key hex for `index`. Caller frees the string. Sensitive.
 */
char *aero_wallet_export_private_key(AeroWallet *w,
                                     uint32_t index);

/**
 * EIP-191 personal_sign of `message` (UTF-8) with account `index`. Returns 0x-prefixed 65-byte
 * signature hex; null on error. Caller frees the string.
 */
char *aero_wallet_sign_message(AeroWallet *w,
                               uint32_t index,
                               const char *message);

/**
 * Recover the signer address of an EIP-191 personal_sign `signature` over `message`. Returns the
 * checksummed address hex; null on error (bad signature). Caller frees the string.
 */
char *aero_wallet_verify_message(const char *message,
                                 const char *signature);

/**
 * Track an ERC20 token in the wallet's Tokens/Assets panel.
 */
int aero_wallet_add_token(AeroWallet *w,
                          const char *address,
                          const char *symbol,
                          uint8_t decimals);

int aero_wallet_remove_token(AeroWallet *w,
                             const char *address);

/**
 * JSON array of tracked tokens. Caller frees the string.
 */
char *aero_wallet_tokens(AeroWallet *w);

/**
 * Per-wallet metadata JSON blob (labels/contacts/notes/funded). "" if none. Caller frees. This is
 * stored encrypted inside the wallet file, not in plaintext settings.
 */
char *aero_wallet_metadata(AeroWallet *w);

/**
 * Replace the per-wallet metadata JSON blob. Persisted (encrypted) on the next `aero_wallet_save`.
 * Returns 0 on success, -1 on error.
 */
int aero_wallet_set_metadata(AeroWallet *w,
                             const char *json);

/**
 * Configure the Tor-routed RPC provider.
 * `endpoints_json` is a JSON array of RPC URLs; `socks_proxy` may be NULL to disable Tor.
 * With no proxy, remote endpoints are refused unless `allow_clearnet` is true (a deliberate,
 * IP-exposing opt-out of Tor); localhost endpoints (your own node / Helios) are always allowed.
 */
int aero_wallet_set_provider(AeroWallet *w,
                             uint64_t chain_id,
                             const char *endpoints_json,
                             const char *socks_proxy,
                             bool allow_clearnet,
                             uint64_t timeout_secs);

/**
 * ETH balance for `index` as JSON `BalanceInfo`. Caller frees the string.
 */
char *aero_wallet_eth_balance(AeroWallet *w,
                              uint32_t index);

/**
 * Native + tracked-token balances for accounts `0..num_accounts` in one batched request.
 * Returns JSON `{ native_symbol, accounts: [ { index, native_raw, native_formatted,
 * native_symbol, tokens: [ { address, symbol, decimals, raw, formatted } ] } ] }`.
 * Caller frees the string.
 */
char *aero_wallet_all_balances(AeroWallet *w,
                               uint32_t num_accounts);

/**
 * ERC20 balance as JSON `BalanceInfo`. Caller frees the string.
 */
char *aero_wallet_erc20_balance(AeroWallet *w,
                                const char *token,
                                uint32_t index);

/**
 * Suggested EIP-1559 fees as JSON `FeeSuggestion`. Caller frees the string.
 */
char *aero_wallet_suggest_fees(AeroWallet *w);

/**
 * ETH/USD price (from the on-chain Chainlink feed, over Tor) as a decimal string. Caller frees.
 */
char *aero_wallet_eth_usd_price(AeroWallet *w);

/**
 * USD price of the connected chain's native coin (Chainlink on mainnet, CoinGecko elsewhere).
 * Decimal string; caller frees.
 */
char *aero_wallet_native_usd_price(AeroWallet *w);

/**
 * Deepest DEX pool USD liquidity for a token (via DexScreener over Tor), as a decimal string
 * ("0" on error / no pools). Caller frees the string.
 */
char *aero_wallet_token_liquidity_usd(AeroWallet *w,
                                      const char *token);

/**
 * Resolve an ERC-20's symbol + decimals (over Tor) as JSON `{"symbol","decimals"}`. Used by the
 * Send token picker when the user pastes an arbitrary contract address. Caller frees the string.
 */
char *aero_wallet_erc20_metadata(AeroWallet *w,
                                 const char *token);

/**
 * USD -> fiat conversion rate for `currency` (e.g. "eur"), via CoinGecko over Tor. 1.0 for "usd"
 * or on error. Used for the Settings fiat-currency display option. Caller frees the string.
 */
char *aero_wallet_fiat_per_usd(AeroWallet *w,
                               const char *currency);

/**
 * Current chain head block number (0 on error). Used for cheap new-block polling.
 */
uint64_t aero_wallet_block_number(AeroWallet *w);

/**
 * Market prices for the Home tickers as JSON `{"xmr_usd","xmr_chg","eth_usd","eth_chg"}` (fetched
 * over Tor). Caller frees the string.
 */
char *aero_wallet_market_prices(AeroWallet *w);

/**
 * Send ETH; returns JSON `SendResult` with the tx hash. `max_fee_wei`/`max_priority_wei` may be
 * NULL/"0" for an automatic fee. Caller frees the string.
 */
char *aero_wallet_send_eth(AeroWallet *w,
                           uint32_t from_index,
                           const char *to,
                           const char *amount_wei,
                           const char *max_fee_wei,
                           const char *max_priority_wei,
                           uint64_t nonce);

/**
 * Send an ERC20 token; returns JSON `SendResult`. Fee/nonce args as in `aero_wallet_send_eth`.
 */
char *aero_wallet_send_erc20(AeroWallet *w,
                             uint32_t from_index,
                             const char *token,
                             const char *to,
                             const char *amount_units,
                             const char *max_fee_wei,
                             const char *max_priority_wei,
                             uint64_t nonce);

/**
 * "Pay to many": send to several recipients (one tx each, sequential nonces). `recipients_json` is
 * a JSON array of `["0xto","amountBaseUnits"]` pairs; `token` empty = native, else ERC-20 address.
 * Returns a JSON array of `{to, tx_hash}` / `{to, error}`. Caller frees the string.
 */
char *aero_wallet_send_many(AeroWallet *w,
                            uint32_t from_index,
                            const char *recipients_json,
                            const char *token,
                            const char *max_fee_wei,
                            const char *max_priority_wei);

/**
 * Broadcast an already-signed raw transaction (0x RLP hex) over the wallet's RPC/Tor. Returns JSON
 * `SendResult`. Works for watch-only wallets too (no keys needed). Caller frees the string.
 */
char *aero_wallet_broadcast_raw(AeroWallet *w,
                                const char *raw_hex);

/**
 * Build an UNSIGNED transaction (resolves nonce/gas/fees over the network) as JSON, for air-gapped
 * signing. `token` empty = native (uses `amount_wei`), else ERC-20 transfer (`amount_units`).
 * `nonce` = u64::MAX for automatic. Caller frees the string.
 */
char *aero_wallet_build_unsigned(AeroWallet *w,
                                 uint32_t from_index,
                                 const char *to,
                                 const char *amount_wei,
                                 const char *token,
                                 const char *amount_units,
                                 const char *max_fee_wei,
                                 const char *max_priority_wei,
                                 uint64_t nonce);

/**
 * Sign an unsigned-tx JSON (from `aero_wallet_build_unsigned`) with the local key; returns the 0x
 * raw RLP hex (no network needed — runs offline). Null on error. Caller frees the string.
 */
char *aero_wallet_sign_unsigned(AeroWallet *w,
                                const char *json);

/**
 * Cancel a pending tx by broadcasting a 0-value self-send at `nonce` with a (bumped) fee. Returns
 * JSON `SendResult`. Caller frees the string.
 */
char *aero_wallet_cancel_tx(AeroWallet *w,
                            uint32_t from_index,
                            uint64_t nonce,
                            const char *max_fee_wei,
                            const char *max_priority_wei);

/**
 * ERC20 transfer history as a JSON array of `HistoryItem`. `from_block` is a hex block number
 * or "earliest"/"latest". Caller frees the string.
 */
char *aero_wallet_erc20_history(AeroWallet *w,
                                const char *token,
                                uint32_t index,
                                const char *from_block);

/**
 * Full account history (native ETH + all ERC20 transfers) for `index`, fetched from a block
 * explorer over Tor, as a JSON array of `HistoryItem`. Caller frees the string.
 */
char *aero_wallet_account_history(AeroWallet *w,
                                  uint32_t index);

/**
 * Scan every common Ethereum derivation scheme for balances (Electrum-style multi-path recovery),
 * registering funded addresses as accounts and returning their unified indices as a JSON array.
 * Mutates the wallet, so it takes `&mut`. Caller frees the string.
 */
char *aero_wallet_scan_funded(AeroWallet *w,
                              uint32_t gap_limit);

/**
 * Owned NFT collections (ERC-721 + ERC-1155) for an account as a JSON array. Caller frees.
 */
char *aero_wallet_account_nfts(AeroWallet *w,
                               uint32_t index);

/**
 * Fetch an image URL over Tor, hex-encoded ("" on error). Caller frees the string.
 */
char *aero_wallet_fetch_image(AeroWallet *w,
                              const char *url);

/**
 * Convert a human decimal string to base units (returns decimal string). Caller frees.
 */
char *aero_parse_units(const char *amount,
                       uint8_t decimals);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AERO_CORE_H */
